In [623]:
import numpy as np 
import pandas as pd

In [624]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [625]:
df = pd.read_csv('gurgaon_data.csv')

In [626]:
df.head()

,property_name,propert_type,society,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [627]:
df.shape

(3961, 20)

In [628]:
df.duplicated().sum()

0

In [629]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   propert_type     3961 non-null   object
 2   society          3960 non-null   object
 3   price_in_crore   3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area_in_sqft     3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [630]:
df.isnull().sum()

property_name         0
propert_type          0
society               1
price_in_crore       20
price_per_sqft       20
area_in_sqft         20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [631]:
df.insert(loc = 3 , column='sector' , value = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip().str.lower())

In [632]:
df.head()

,property_name,propert_type,society,sector,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,krishna colony,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,ashok vihar,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,sohna,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,sector 61,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,sector 92,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [633]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 111                                                    22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 52                                                     14
rajendra park                                                 14
dlf phase 5                                                   14
sector 1 imt manesar                                          14
sector 76                                                     14
sector 53                                                     14
gwal pahari                                                   14
sector 3                                                      14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
sohna road                                                    12
sector 93                                                     12
sector 38                                                     12
sector 39                                                     12
sector 31                                                     12
sector 50                                                     12
uppals southend                                               12
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 9a                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
ashok vihar phase 2                                            9
sector 55                                                      9
sector 4                                                       9
sector 95a                                                     9
south city 1                                                   9
c block sushant lok phase 1                                    8
sector 59                                                      8
palam vihar extension                                          8
dwarka expressway                                              8
sector 57                                                      8
sector 40                                                      8
sector 43                                                      8
sector 10a                                                     8
sector 89 a                                                    8
mehrauli  road                                                 8
malibu town                                                    8
sector 51                                                      7
new colony                                                     7
surat nagar 1                                                  7
sector 58                                                      7
sector 11                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
sector 26                                                      7
sector 5                                                       6
sector 1                                                       6
jacobpura                                                      6
ashok vihar                                                    6
jyoti park                                                     6
rajiv nagar                                                    6
saraswati vihar                                                5
subhash nagar                                                  5
new palam vihar                                                5
sector 30                                                      5
sector 2                                                       5
ansal plaza                                                    5
sushant lok phase 2                                            5
sector 23a                                                     5
greenwood city                                                 5
sector 80                                                      5
arjun nagar                                                    5
chakkarpur                                                     5
sector 28                                                      5
manesar                                                        5
dayanand colony                                                5
sector 9                                                       5
sector 105                                                     5
adarsh nagar                                                   4
valley view estate                                             4
shivpuri                                                       4
shivaji nagar                                                  4
vishnu garden                                                  4
madanpuri                                                      4
ravi nagar                                                     4
dharam colony                                                  4
bhim nagar                                                     4
devilal colony                                                 4
bhondsi                                                        4
krishna colony                                                 4
sector 45                                                      4
sector 3a                                                      4
baldev nagar                                                   4
surya vihar                                                    4
sector 36                                                      4
sector 12                                                      4
new                                                            4
garhi harsaru                                                  4
suncity                                                        4
sector 6                                                       4
sector 12a                                                     4
imt manesar                                                    4
sector 17                                                      4
maruti kunj                                                    3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 15                                                      3
sector 8                                                       3
sector 73                                                      3
sector 17b                                                     3
sector 23                                                      3
patel nagar                                                    3
sector 110 a                                                   3
sector 27                                                      3
mg road                                                        3
prem nagar                                                     3
sector 17a                                                     3
gandhi nagar                                                   3
sector 88b                                                     3
shakti nagar                                                   3
a block sushant lok phase 1                                    3
mayfield garden                                                2
rosewood                                                       2
mohan nagar                                                    2
hira nagar                                                     2
daulatabad                                                     2
farukhnagar                                                    2
rajiv chowk                                                    2
new basti                                                      2
, delhi ncr                                                    2
sheetla colony                                                 2
surat nagar phase 2                                            2
manohar nagar                                                  2
pratap nagar                                                   2
surat nagar                                                    2
acharya puri                                                   2
west rajiv nagar                                               2
sohna  road                                                    2
bissar                                                         2
golf course ext road                                           2
bhawani enclave                                                2
sector 21                                                      2
faridabad road                                                 2
samaspur                                                       2
lajpat nagar                                                   2
sispal vihar                                                   2
sushant lok                                                    2
shankar vihar                                                  2
golf course road                                               2
nars                                                           2
new palam vihar phase 2                                        2
iffco chowk                                                    2
sector 24                                                      2
sector 32                                                      2
shanti nagar                                                   2
ambience island                                                2
sector 15 part 1                                               2
sector 41                                                      2
new palam vihar phase 1                                        2
sector-2 sohna                                                 2
block a surya vihar                                            2
sector 15 part 2                                               2
sector-11 sohna                                                2
new jyoti park                                                 1
mahavir pura                                                   1
kanahi                                                         1
sector 37b                                                     1
sector 17c                                                     1
damdma                                                         1
sector-5 sheetla colony                                        1
laxman vihar, railway road,                                    1
park view                                                      1
naharpur rupa                                                  1
sadar bazar                                                    1
rattan garden                                                  1
mahalaxmi garden, rajendra place                               1
udyog vihar phase 1                                            1
shivji park colony                                             1
g block dlf city phase 1                                       1
saraswati enclave                                              1
ravi nager basai road                                          1
begampur khatola                                               1
v block dlf phase 3                                            1
south city                                                     1
sector-7 hous                                                  1
sector 42                                                      1
b1 block sector 57                                             1
rajiv colony                                                   1
garauli kalan                                                  1
near sector 1 market                                           1
laxmna vihar, phase 2                                          1
huda saraswati vihar                                           1
bhimgarh kheri phase 3                                         1
near euro                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ansal's palam vihar                                            1
alipur                                                         1
devi lal colony gali no 12 gurgaon nr omkar public school      1
dhankot                                                        1
jacobpura near sadar bazar                                     1
block g sector-57                                              1
ashok vihar phase 3                                            1
sector-35 sohna                                                1
sector 5 chowk                                                 1
old delhi road, opp sector-14                                  1
block h ashok vihar phase iii extension                        1
ashok vihar phase i                                            1
nirvana country pocket h                                       1
near nand hospital                                             1
bhora kalan                                                    1
sector 9b                                                      1
saroop garden rajendra park                                    1
khandsa                                                        1
sector 4 urban estate                                          1
bptp                                                           1
godrej aria , sector 79 ,                                      1
sector 21a faridabad                                           1
kheri                                                          1
hsiidc plot sector 1 imt manesar                               1
jat colony,fazilpur/taj nagar road                             1
gopal nagar, garhi ghasita, sonipat                            1
sector-5 sohna                                                 1
urban estate, sector 5                                         1
tekchand nagar                                                 1
vir nagar                                                      1
heritage city                                                  1
anand garden, sector-105                                       1
om nagar                                                       1
sai kunj                                                       1
sultanpur                                                      1
ram nagar                                                      1
sector 13                                                      1
hno 13 sagar enclave sura                                      1
civil l                                                        1
near khandsa road                                              1
new colony, sector 7                                           1
near pataudi chowk                                             1
cyber city                                                     1
pataudi road                                                   1
lucknow                                                        1
part 3 sector 5                                                1
ats marigold                                                   1
sector 37a                                                     1
carterpuri village                                             1
Name: count, dtype: int64

In [634]:
df['sector'].value_counts().sum()

3961

In [635]:
df['sector'].isnull().shape

(3961,)

In [636]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [637]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     65
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector 43                                                     53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 49                                                     48
sector 67                                                     48
sector 28                                                     47
sector 66                                                     46
sector 103                                                    45
sector 25                                                     43
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 7                                                      39
sector 106                                                    38
sector 4                                                      36
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 12                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 24                                                     24
sector 57                                                     24
sector 112                                                    24
sector 88a                                                    23
sector 14                                                     23
sector 33                                                     23
sector 105                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 11                                                     21
sector 3                                                      20
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 47                                                     19
gwal pahari                                                   18
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 52                                                     14
sector 76                                                     14
sector 53                                                     14
sector 1 manesar                                              14
sector 55                                                     14
sector 36a                                                    13
sector 46                                                     13
sector 4 phase 2                                              13
sector 6                                                      13
sector 9                                                      13
sector 39                                                     12
sector 93                                                     12
sector 38                                                     12
sector 31                                                     12
sohna road road                                               12
sector 41                                                     11
sector 3 phase 3 extension                                    11
sector 9a                                                     11
sector 1a manesar                                             10
sector 13                                                     10
manesar                                                        9
sector 45                                                      9
sector 95a                                                     9
sector 3 phase 2                                               9
sector 89 a                                                    8
sector 8                                                       8
sector 23                                                      8
c block sector 43                                              8
sector 17                                                      8
sector 2 extension                                             8
sector 10a                                                     8
sector 40                                                      8
dwarka expressway                                              8
sector 59                                                      8
sector 36 sohna road                                           7
sector 51                                                      7
sector 58                                                      7
sector 5                                                       6
sector 1                                                       6
sector 21                                                      6
sector 30                                                      5
sector 23a                                                     5
new sector 2                                                   5
sector 80                                                      5
sector 3a                                                      4
sector 12a                                                     4
sector 36                                                      4
new                                                            4
sector 27                                                      3
b block sector 43                                              3
sector 17a                                                     3
sector 88b                                                     3
maruti kunj                                                    3
sector 15                                                      3
sector 73                                                      3
sector 110 a                                                   3
patel nagar                                                    3
a block sector 43                                              3
sector 17b                                                     3
new sector 2 phase 1                                           2
sector 15 part 2                                               2
nars                                                           2
pratap nagar                                                   2
farukhnagar                                                    2
mohan nagar                                                    2
rosewood                                                       2
hira nagar                                                     2
daulatabad                                                     2
new basti                                                      2
, delhi ncr                                                    2
surat nagar phase 2                                            2
acharya puri                                                   2
mayfield garden                                                2
sohna road  road                                               2
manohar nagar                                                  2
west sector 13                                                 2
sheetla colony                                                 2
rajiv chowk                                                    2
surat nagar                                                    2
bissar                                                         2
sushant lok                                                    2
bhawani enclave                                                2
sector 32                                                      2
golf course road                                               2
block a sector 21                                              2
sector-2 sohna road                                            2
ambience island                                                2
shanti nagar                                                   2
sector 15 part 1                                               2
sector-11 sohna road                                           2
iffco chowk                                                    2
faridabad road                                                 2
lajpat nagar                                                   2
golf course ext road                                           2
samaspur                                                       2
sispal vihar                                                   2
new sector 2 phase 2                                           2
shankar vihar                                                  2
damdma                                                         1
g block dlf city phase 1                                       1
sector 37b                                                     1
sector 12 near sadar bazar                                     1
mahavir pura                                                   1
sector-7 hous                                                  1
new sector 7                                                   1
sadar bazar                                                    1
rattan garden                                                  1
sector-5 sheetla colony                                        1
sector 4, railway road,                                        1
shivji park colony                                             1
udyog vihar phase 1                                            1
naharpur rupa                                                  1
park view                                                      1
mahasector 11, rajendra place                                  1
saroop garden sector 105                                       1
alipur                                                         1
ravi nager basai road                                          1
laxmna vihar, phase 2                                          1
v block sector 24                                              1
rajiv colony                                                   1
south city                                                     1
sector 42                                                      1
garauli kalan                                                  1
b1 block sector 57                                             1
near sector 1 market                                           1
huda sector 28                                                 1
begampur khatola                                               1
bhimgarh kheri phase 3                                         1
near euro                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
saraswati enclave                                              1
sector 3 phase 3                                               1
devi lal colony gali no 12 gurgaon nr omkar public school      1
dhankot                                                        1
ansal's sector 2                                               1
hno 13 sagar enclave sura                                      1
tekchand nagar                                                 1
gopal nagar, garhi ghasita, sonipat                            1
bhora kalan                                                    1
sector 9b                                                      1
cyber city                                                     1
ats marigold                                                   1
sector 37a                                                     1
carterpuri village                                             1
kheri                                                          1
jat colony,fazilpur/taj nagar road                             1
sector 17c                                                     1
anand garden, sector-105                                       1
sector-5 sohna road                                            1
sector 5 chowk                                                 1
old delhi road, opp sector-14                                  1
hsiidc plot sector 1 manesar                                   1
sector 50 pocket h                                             1
sector 21a faridabad                                           1
godrej aria , sector 79 ,                                      1
sector-35 sohna road                                           1
near nand hospital                                             1
near pataudi chowk                                             1
sector 3 phase i                                               1
block h sector 3 phase iii extension                           1
om nagar                                                       1
kanahi                                                         1
block g sector-57                                              1
ram nagar                                                      1
sector 4 urban estate                                          1
vir nagar                                                      1
heritage city                                                  1
sai kunj                                                       1
pataudi road                                                   1
lucknow                                                        1
part 3 sector 5                                                1
sultanpur                                                      1
civil l                                                        1
near khandsa road                                              1
sector 7, sector 7                                             1
urban estate, sector 5                                         1
khandsa                                                        1
bptp                                                           1
Name: count, dtype: int64

In [638]:
df['sector'].value_counts().shape

(250,)

In [639]:
a = df['sector'].value_counts()[df['sector'].value_counts()>= 3]

In [640]:
a

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 88a                     23
sector 14                      23
sector 33                      23
sector 105                     23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 82a                     20
sector 22                      20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 52                      14
sector 76                      14
sector 53                      14
sector 1 manesar               14
sector 55                      14
sector 36a                     13
sector 46                      13
sector 4 phase 2               13
sector 6                       13
sector 9                       13
sector 39                      12
sector 93                      12
sector 38                      12
sector 31                      12
sohna road road                12
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 45                       9
sector 95a                      9
sector 3 phase 2                9
sector 89 a                     8
sector 8                        8
sector 23                       8
c block sector 43               8
sector 17                       8
sector 2 extension              8
sector 10a                      8
sector 40                       8
dwarka expressway               8
sector 59                       8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 5                        6
sector 1                        6
sector 21                       6
sector 30                       5
sector 23a                      5
new sector 2                    5
sector 80                       5
sector 3a                       4
sector 12a                      4
sector 36                       4
new                             4
sector 27                       3
b block sector 43               3
sector 17a                      3
sector 88b                      3
maruti kunj                     3
sector 15                       3
sector 73                       3
sector 110 a                    3
patel nagar                     3
a block sector 43               3
sector 17b                      3
Name: count, dtype: int64

In [641]:
a.index

Index(['sohna road', 'sector 102', 'sector 85', 'sector 92', 'sector 69',
       'sector 81', 'sector 65', 'sector 90', 'sector 109', 'sector 79',
       ...
       'b block sector 43', 'sector 17a', 'sector 88b', 'maruti kunj',
       'sector 15', 'sector 73', 'sector 110 a', 'patel nagar',
       'a block sector 43', 'sector 17b'],
      dtype='object', name='sector', length=131)

In [642]:
df = df[df['sector'].isin(a.index)]

In [643]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 24                      24
sector 112                     24
sector 33                      23
sector 105                     23
sector 14                      23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 3                       20
sector 78                      19
sector 47                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 63                      15
sector 76                      14
sector 55                      14
sector 52                      14
sector 53                      14
sector 1 manesar               14
sector 6                       13
sector 36a                     13
sector 4 phase 2               13
sector 46                      13
sector 9                       13
sector 93                      12
sector 38                      12
sector 39                      12
sector 31                      12
sohna road road                12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 95a                      9
sector 45                       9
sector 3 phase 2                9
sector 2 extension              8
sector 59                       8
dwarka expressway               8
sector 40                       8
c block sector 43               8
sector 23                       8
sector 10a                      8
sector 8                        8
sector 17                       8
sector 89 a                     8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 1                        6
sector 5                        6
sector 21                       6
sector 23a                      5
sector 80                       5
new sector 2                    5
sector 30                       5
new                             4
sector 12a                      4
sector 36                       4
sector 3a                       4
a block sector 43               3
sector 17b                      3
sector 73                       3
sector 88b                      3
maruti kunj                     3
sector 17a                      3
b block sector 43               3
sector 15                       3
sector 110 a                    3
patel nagar                     3
sector 27                       3
Name: count, dtype: int64

In [644]:
df['sector'].value_counts().shape

(131,)

In [645]:
df['sector'].shape

(3803,)

In [646]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [647]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 43                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 84                      51
sector 26                      50
sector 4                       49
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     24
sector 3                       24
sector 57                      24
sector 24                      24
sector 105                     23
sector 14                      23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 110                     19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 91                      17
sector 62                      17
sector 99                      16
sector 63                      15
sector 60                      15
sector 53                      14
sector 52                      14
sector 55                      14
sector 76                      14
sector 36a                     13
sector 6                       13
sector 46                      13
sector 23                      13
sector 9                       13
sector 38                      12
sohna road road                12
sector 31                      12
sector 93                      12
sector 39                      12
sector 36                      11
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 3 phase 2                9
sector 45                       9
sector 8                        8
dwarka expressway               8
sector 59                       8
sector 17                       8
sector 10a                      8
sector 40                       8
sector 51                       7
sector 58                       7
sector 15                       6
sector 1                        6
sector 21                       6
sector 5                        6
sector 80                       5
sector 30                       5
new sector 2                    5
new                             4
sector 17a                      3
sector 88b                      3
sector 73                       3
sector 17b                      3
sector 27                       3
Name: count, dtype: int64

In [648]:
df['sector'].value_counts().shape

(114,)

In [649]:
df['sector'] = df['sector'].str.replace('sector 37d','sector 37')
df['sector'] = df['sector'].str.replace('sector 37c','sector 37')
df['sector'] = df['sector'].str.replace('sector 99a','sector 99')
df['sector'] = df['sector'].str.replace('manesar','sector 1')
df['sector'] = df['sector'].str.replace('gwal pahari','sector 55')
df['sector'] = df['sector'].str.replace('sector 67a','sector 67')
df['sector'] = df['sector'].str.replace('sector 82a','sector 82')
df['sector'] = df['sector'].str.replace('sector 63a','sector 63')
df['sector'] = df['sector'].str.replace('sector 36a','sector 36')
df['sector'] = df['sector'].str.replace('sector 9a','sector 9')
df['sector'] = df['sector'].str.replace('sector 10a','sector 10')
df['sector'] = df['sector'].str.replace('sector 88b','sector 88')
df['sector'] = df['sector'].str.replace('sector 17b','sector 17')
df['sector'] = df['sector'].str.replace('sector 17a','sector 17')
df['sector'] = df['sector'].str.replace('new sector 2','sector 110')
df['sector'] = df['sector'].str.replace('sector 3 phase 3 extension','sector 3')
df['sector'] = df['sector'].str.replace('sector 3 phase 2','sector 3')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')

In [650]:
df['sector'].value_counts().shape

(99,)

In [651]:
df['sector'].value_counts()

sector
sohna road           175
sector 37            121
sector 102           113
sector 85            110
sector 92            104
sector 69             94
sector 81             90
sector 90             90
sector 65             90
sector 109            88
sector 79             80
sector 33             74
sector 104            73
sector 67             70
sector 83             69
sector 86             67
sector 43             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 82             62
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 84             51
sector 26             50
sector 4              49
sector 49             48
sector 99             48
sector 28             47
sector 66             46
sector 103            45
sector 3              44
sector 113            43
sector 25             43
sector 61             42
sector 7              39
sector 1              39
sector 106            38
sector 12             37
sector 63             33
sector 55             32
sector 54             31
sector 68             30
sector 72             29
sector 77             29
sector 71             27
sector 57             24
sector 112            24
sector 36             24
sector 110            24
sector 24             24
sector 9              24
sector 105            23
sector 14             23
sector 88a            23
sector 111            22
sector 11             21
sector 22             20
sector 78             19
sector 47             19
sector 74             18
sector 62             17
sector 91             17
sector 60             15
sector 76             14
sector 17             14
sector 52             14
sector 53             14
sector 46             13
sector 23             13
sector 6              13
sector 31             12
sector 39             12
sector 93             12
sector 38             12
sector 41             11
sector 13             10
sector 45              9
sector 10              8
sector 8               8
dwarka expressway      8
sector 40              8
sector 59              8
sector 58              7
sector 51              7
sector 21              6
sector 5               6
sector 15              6
sector 30              5
sector 80              5
new                    4
sector 88              3
sector 73              3
sector 27              3
Name: count, dtype: int64

In [652]:
df[df['sector'] == 'new']

,property_name,propert_type,society,sector,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2045,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2803,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2895,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2960,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [653]:
df.loc[2803,'sector'] = 'sector 37'
df.loc[2960,'sector'] = 'sector 92'
df.loc[2895,'sector'] = 'sector 90'
df.loc[2045,'sector'] = 'sector 76'

In [654]:
df[df['sector'] == 'dwarka expressway']

,property_name,propert_type,society,sector,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
6,3 BHK Flat in Dwarka Expressway Gurgaon,flat,the cocoon,dwarka expressway,2.00,13333.0,1500.0,Super Built up area 1500(139.35 sq.m.),3,3,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",5.0,NaN,0 to 1 Year Old,"['Shri Multispeciality Hospital', 'Esic Hospit...",Residential apartment for sell.The property co...,[],NaN,NaN
116,3 BHK Flat in Dwarka Expressway Gurgaon,flat,ramprastha city,dwarka expressway,1.30,9027.0,1440.0,Super Built up area 1440(133.78 sq.m.),3,3,2,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",3.0,NaN,By 2023,"['Raheja Mall', 'HUDA Market, Sector 14', 'Gur...",We are the proud owners of this 3 bhk apartmen...,[],NaN,NaN
124,3 BHK Flat in Dwarka Expressway Gurgaon,flat,ramprastha city,dwarka expressway,1.30,9285.0,1400.0,Super Built up area 1400(130.06 sq.m.),3,3,2,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",3.0,NaN,By 2023,"['Raheja Mall', 'HUDA Market, Sector 14', 'Gur...",We are the proud owners of this 3 bhk apartmen...,[],NaN,NaN
180,3 BHK Flat in Dwarka Expressway Gurgaon,flat,experion heartsong,dwarka expressway,1.08,6150.0,1756.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
388,3 BHK Flat in Dwarka Expressway Gurgaon,flat,hero homes,dwarka expressway,1.60,7825.0,2045.0,Super Built up area 1689(156.91 sq.m.),3,3,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Gol Market', 'Gurdwara Baba Deep Singh', 'Gu...",We are the proud owners of this 3 bhk apartmen...,"['2 Wardrobe', '2 Fan', '2 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
2757,3 BHK Flat in Dwarka Expressway Gurgaon,flat,ansals highland park,dwarka expressway,1.20,6185.0,1940.0,Built Up area: 1940 (180.23 sq.m.),3,3,3+,servant room,"Sector 103, Dwarka Expressway, Gurugram, Harya...",4.0,NaN,Under Construction,"['Dr. Hitesh Dawar', 'Bhardwaj Hospital', 'R K...",This three bedroom for sale comes with an affo...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2825,3 BHK Flat in Dwarka Expressway Gurgaon,flat,smart world one,dwarka expressway,1.65,5933.0,2781.0,Carpet area: 2785 (258.73 sq.m.),3,4,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",6.0,NaN,Under Construction,"['Shri Multispeciality Hospital', 'Esic Hospit...",Residential apartment for sell.Located on 6th ...,[],NaN,NaN
3521,5 Bedroom House for sale in Dwarka Expressway ...,house,rattan vihar rajendra park,dwarka expressway,0.85,14166.0,600.0,Plot area 600(55.74 sq.m.),5,5,3+,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Shri Multispeciality Hospital', 'Esic Hospit...",Looking for buyer to purchase our house/villa ...,[],NaN,NaN

In [655]:
df.loc[6,'sector'] = 'sector 9'
df.loc[116,'sector'] = 'sector 14'
df.loc[124,'sector'] = 'sector 14'
df.loc[180,'sector'] = 'sector 108'
df.loc[388,'sector'] = 'sector 9'
df.loc[2757,'sector'] = 'sector 103'
df.loc[2825,'sector'] = 'sector 9'
df.loc[3521,'sector'] = 'sector 9'

In [656]:
df['sector'].value_counts().shape

(97,)

In [657]:
df.shape

(3803, 21)

In [658]:
df['sector'].value_counts()

sector
sohna road    175
sector 37     122
sector 102    113
sector 85     110
sector 92     105
sector 69      94
sector 90      91
sector 65      90
sector 81      90
sector 109     88
sector 79      80
sector 33      74
sector 104     73
sector 67      70
sector 83      69
sector 43      67
sector 86      67
sector 95      66
sector 50      65
sector 89      64
sector 2       63
sector 82      62
sector 108     60
sector 107     60
sector 56      57
sector 48      56
sector 70a     54
sector 70      53
sector 84      51
sector 26      50
sector 4       49
sector 99      48
sector 49      48
sector 28      47
sector 103     46
sector 66      46
sector 3       44
sector 113     43
sector 25      43
sector 61      42
sector 1       39
sector 7       39
sector 106     38
sector 12      37
sector 63      33
sector 55      32
sector 54      31
sector 68      30
sector 77      29
sector 72      29
sector 9       28
sector 71      27
sector 14      25
sector 24      24
sector 112     24
sector 57      24
sector 36      24
sector 110     24
sector 88a     23
sector 105     23
sector 111     22
sector 11      21
sector 22      20
sector 78      19
sector 47      19
sector 74      18
sector 91      17
sector 62      17
sector 60      15
sector 76      15
sector 53      14
sector 17      14
sector 52      14
sector 6       13
sector 46      13
sector 23      13
sector 39      12
sector 31      12
sector 93      12
sector 38      12
sector 41      11
sector 13      10
sector 45       9
sector 8        8
sector 59       8
sector 10       8
sector 40       8
sector 51       7
sector 58       7
sector 15       6
sector 21       6
sector 5        6
sector 30       5
sector 80       5
sector 88       3
sector 73       3
sector 27       3
Name: count, dtype: int64

In [659]:
df.sample(5)

,property_name,propert_type,society,sector,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1265,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,sector 70,1.50,7692.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",7.0,South,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Shree vardhman vactoria sector 70\n Additional...,"['4 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2006,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,sector 33,2.15,13522.0,1590.0,Super Built up area 1590(147.72 sq.m.),3,3,3+,not available,"Sector-33 Sohna, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",It is located at one of the promising location...,"['3 Wardrobe', '3 AC', 'No Bed', 'No Chimney',...","['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...",NaN
777,4 BHK Flat in Sector 92 Gurgaon,flat,sare homes,sector 92,1.18,5207.0,2266.0,Carpet area: 2266 (210.52 sq.m.),4,4,3,servant room,"802, Sector 92 Gurgaon, Gurgaon, Haryana",8.0,North,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Sare homes is one of gurgaon's most sought aft...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3747,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,sector 109,6.25,10035.0,6228.0,Plot area 692(578.6 sq.m.),5,7,3+,"pooja room,study room,servant room,store room","A123, Sector 109 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",Its a 5bhk 692 duplex villa in sobha internati...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1941,3 BHK Flat in Sector 67 Gurgaon,flat,ansal api esencia,sector 67,1.00,6435.0,1554.0,Super Built up area 1554(144.37 sq.m.),3,3,3+,not available,"Sector 67 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Proposed Metro corridor', 'N.H-8', 'Golf Cou...",We are the proud owners of this 3 bhk apartmen...,[],['Private Garden / Terrace'],"['Green Area5 out of 5', 'Construction4 out of..."

In [660]:
df.drop(columns =['property_name','address','description','rating'],inplace = True)

In [661]:
df.head()

,propert_type,society,sector,price_in_crore,price_per_sqft,area_in_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,maa bhagwati residency,sector 7,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...","['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,flat,apna enclave,sector 3,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,flat,tulsiani easy in homes,sohna road,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,flat,smart world orchard,sector 61,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,2.0,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,flat,parkwood westend,sector 92,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",[],NaN

In [662]:
df.shape

(3803, 17)

In [663]:
df.duplicated().sum()

122

In [664]:
df.to_csv('merged_data_cleaned.csv',index = False)